version: '3.9'

services:  
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Pass@w0rd!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    restart: always